version: "3"
services:
    metricso:
        build: .
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
            - "443:443"
        links:
            - metricso_rabbit

    metricso_rabbit:
        image: rabbitmq:3.7.3-management
        ports:
            - "5678:5672"
            - "15678:15672"
